### ISSUE TITLE
Mongoinspector not automatically unshrinking, stays expanded all the time

### ISSUE THREAD

**Issue by jasonxeno** [msavin/MongoInspector#10]
I see in the demo the window is supposed to shrink when you click off of it. In my app it doesn't do that, and just stays expanded forever, so there must be some type of collision on that focus detection. Any ideas?

Good work on the package!

**Comment by krawalli** [comment]
Have a look in mongoinspector_body.js
~~~javascript
 Template.MongoInspector_header.events({
        'click': function () {
            $("#MongoInspector").hide();
        }
    });
~~~

and replace that with
~~~javascript
Template.MongoInspector_header.events({
  'click': function () {
    if ($('#MongoInspector').hasClass('MongoInspector_expand')) {
      $('.MongoInspector_row').removeClass('MongoInspector_row_expand');
      $('#MongoInspector').removeClass('MongoInspector_expand');
    } else {
      $("#MongoInspector").hide();
    }
  }
});
~~~

This will give you on click in the title bar:
- shrink MonogInspector if it was expanded
- hide MongoInspector if it was already shrink-ed

Its not optimized code, since it will walk through the complete DOM-Object (wich in this case is not needed. The whole code needs some rework to benefit from Blaze Template System. However, it should give you what you expected.

**Comment by krawalli** [comment]
@msavin Do you need a explicit pull request to implement this?

**Comment by msavin** [comment]
Nope, coming up :) Thanks for the contribution. I was planning to do it on the individual row level, but your solution looks good too.

**Comment by krawalli** [comment]
this could be marked as fixed, or?

**Comment by msavin** [comment]
All set, thanks again!
